# Generated by Django 2.0.5 on 2018-05-18 03:13

from django.db import migrations, models


def move_title(apps, schema):
    Event = apps.get_model('events', 'Event')
    for event in Event.objects.all().select_related('page_ptr'):
        event.new_title = event.page_ptr.title
        event.save()


def fix_tree(apps, schema):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    try:
        event_ct = ContentType.objects.get_by_natural_key('events', 'event')
        eventindex_ct = ContentType.objects.get_by_natural_key('events', 'eventindex')
        page_ct = ContentType.objects.get_by_natural_key('wagtailcore', 'page')
    except ContentType.DoesNotExist:
        return

    Page = apps.get_model('wagtailcore', 'Page')
    Page.objects\
        .filter(content_type__in=[event_ct, eventindex_ct])\
        .update(content_type=page_ct)


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0040_page_draft_title'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleitem',
            old_name='page',
            new_name='event',
        ),

        migrations.AlterField(
            model_name='event',
            name='page_ptr',
            field=models.OneToOneField('wagtailcore.Page', on_delete=models.CASCADE, primary_key=True),
        ),
        migrations.AddField(
            model_name='event',
            name='new_title',
            field=models.CharField(max_length=255, default=''),
            preserve_default=False,
        ),
        migrations.RunPython(move_title),
        migrations.RenameField(
            model_name='event',
            old_name='new_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='event',
            name='page_ptr',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='event',
            old_name='page_ptr',
            new_name='id',
        ),

        migrations.RemoveField(
            model_name='eventindex',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='EventIndex',
        ),
        migrations.RunPython(fix_tree, None),
    ]
