# Generated by Django 2.0.5 on 2018-07-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_homepage_location_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='ical_feed',
            field=models.URLField(blank=True, default="http://www.google.com/calendar/ical/joshgilli.es_ets7187s9vds2f1j4vsiljtf4k%40group.calendar.google.com/public/basic.ics"),
            preserve_default=False,
        ),
    ]
